### PR TITLE
Updated! Please review again.

### PR DESCRIPTION
**Pull request by lyw0149**
Adjust 'gulp-jscs' and linted based on airbnb code style guide.

### CODE REVIEW

**Comment by ethkim** [comment]
LGTM

**Comment by ethkim** [comment]
It looks like the LGTM doesn't kick in unless you set the MAINTAINERS file in master branch?

https://lgtm.co/docs/overview/

Could you add that file in a separate branch, and get that merged into master branch? Then we can test if the LGTM works as intended. Thanks!

**Comment by ethkim** [comment]
LGTM

**Comment by ifndefdeadmau5** [comment]
LGTM

**Comment by lyw0149** [comment]
Oh. THANKS!! @ethkim. You add MAINTAINERS file. We're not familiar with LGTM and git Features. I thinks we need some documents about it.

**Comment by nlpenguin** [comment]
@lyw0149 You may hit the green button now. #shipit!

**Comment by KaylaKwon** [comment]
Yey~~~ So happy~~~~~~~~

**Pull request merged**
