### PR TITLE
Add .lgtm file

### PR DESCRIPTION
**Pull request by ethkim**
Add the .lgtm file for LGTM configuration.
With this change:
1. Each PR request now only requires 1 LGTM from MAINTAINERS file.
2. Each LGTM can be written as one of:
  -  :shipit:
  -  👍 
  -  LGTM

For more customization, see:

- https://lgtm.co/docs/customize/
- https://lgtm.co/docs/overview/

### CODE REVIEW

**Comment by ifndefdeadmau5** [comment]
Wow. I love this customization

**Comment by ifndefdeadmau5** [comment]
LGTM

**Comment by ethkim** [comment]
Since the point of this PR is to set the min # of reviewers to 1, I'm submitting this.. :)

**Comment by lyw0149** [comment]
Why hamster means good? Cute?

**Pull request merged**
