### PR TITLE
Double relation check.

### PR DESCRIPTION
**Pull request by lyw0149**
1.Double relation checks for individual user data to prevent duplication of activity data.
2.Modify unit test for this.

@nlpenguin @ethkim @KyuaKwon @ace0625

### CODE REVIEW

**Comment by ethkim** [comment]
LGTM except the comment below. Thanks!

**Comment by lyw0149** [comment]
@ethkim what is the comment below?? I can't find...

**Comment by ethkim** [comment]
i meant above. :P about that 100 char line limit.

**Comment by lyw0149** [comment]
@ethkim Checked and changed. I need re-LGTM. Thanks!

**Pull request merged**
